# Ansible
ansible_become_password:

# List of remote-user's public keys
authorized_keys:
  - <key-1>
  - <key-2>

# SSL root certificate secret
root_ca_private_key_passphrase:

# Traefik
traefik_dashboard_admin_password:

# Pihole
pihole_admin_password:

# Portainer
portainer_admin_password:

# NextCloud
nextcloud_admin_password:
nextcloud_database_password:

# Gitea
gitea_database_password: