# Ansible
ansible_become_password:

# List of remote-user public keys
authorized_keys:
  - <key-1>
  - <key-2>

# SSL certificate secrets
certificate_key_passphrase:
root_ca_private_key_passphrase:

# Traefik
traefik_dashboard_admin_password_hash:

# Pihole
pihole_admin_password:

# Postgresql
postgresql_admin_password:

# Portainer
portainer_admin_password_hash:

# NextCloud
nextcloud_admin_password:
nextcloud_database_password:

# Gitea
gitea_database_password: