- block:
    - name: Add service user for GitLab
      user:
        name: "{{ gitlab_service_user }}"
        groups: "{{ service_group }}"
        state: present

    - name: Copy docker compose file
      template:
        src: ../templates/docker-compose.yml.j2
        dest: "{{ gitlab_home_directory }}/docker-compose.yml"
        owner: "{{ gitlab_service_user }}"
        group: "{{ gitlab_service_user }}"
        mode: 0600

    - name: Deploy docker compose stack
      community.docker.docker_compose_v2:
        project_src: "{{ gitlab_home_directory }}"
        files:
          - docker-compose.yml

  become: true